"""Refreshes model_catalog.json's benchmark_choices from OpenRouter, on a
90-day cache, and renders MODEL_CATALOG.md from the same data. Any failure
anywhere in the fetch/rank path (including no OPENROUTER_API_KEY configured)
leaves the existing cache untouched and returns False - install must never
hard-fail on this."""
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

from catalog.families import load_curated_families
from catalog.openrouter_benchmarks import fetch_benchmarks, rank_candidates

_CACHE_DAYS = 90
# NOTE: the bundled catalog file is "models_catalog.json" (plural) - it's the
# same file setup_config.py's load_models_catalog()/_CATALOG_PATH reads, ported
# from the main tool in Task 1. Do not "fix" this to the singular form.
_DEFAULT_CATALOG_PATH = Path(__file__).parent.parent / "models_catalog.json"
_DEFAULT_MD_PATH = Path(__file__).parent.parent / "MODEL_CATALOG.md"

# Mirrors setup_config.py's _TIER_TUNING RAM/VRAM floors - kept in sync by
# hand since these are install-time hardware decisions, not catalog data.
_TIER_FLOORS = {
    "high":     {"min_ram_gb": 0,  "min_vram_gb": 12},
    "mid":      {"min_ram_gb": 0,  "min_vram_gb": 6},
    "cpu_rich": {"min_ram_gb": 16, "min_vram_gb": 0},
    "low":      {"min_ram_gb": 8,  "min_vram_gb": 0},
    "minimal":  {"min_ram_gb": 0,  "min_vram_gb": 0},
}


def _is_stale(fetched_at) -> bool:
    if not fetched_at:
        return True
    dt = datetime.fromisoformat(fetched_at)
    return datetime.now(timezone.utc) - dt > timedelta(days=_CACHE_DAYS)


def _render_markdown(data: dict) -> str:
    lines = [
        "# Model Catalog",
        "",
        f"Auto-refreshed from OpenRouter benchmarks. Last updated: {data.get('fetched_at', 'never')}.",
        "Do not hand-edit this file - it is regenerated by `catalog/refresh_model_catalog.py`.",
        "",
    ]
    for tier_name, tier in data["tiers"].items():
        lines.append(f"## {tier['label']}")
        lines.append("")
        lines.append(f"Default: `{tier['gen_model']}` - {tier['why']}")
        choices = tier.get("benchmark_choices", [])
        if choices:
            lines.append("")
            lines.append("| Rank | Tag | Family | Intelligence Index | Size |")
            lines.append("|---|---|---|---|---|")
            for i, c in enumerate(choices, start=1):
                lines.append(f"| {i} | `{c['tag']}` | {c['family']} | "
                              f"{c['intelligence_index']:.1f} | {c['size_gb']} GB |")
        lines.append("")
    return "\n".join(lines)


def refresh(force: bool = False, catalog_path=None, md_path=None) -> bool:
    """Never raises - any failure (missing/malformed catalog file, network
    error, missing API key, bad response shape) returns False and leaves
    whatever cache exists untouched. Callers (setup_config.py's main(),
    the --refresh-benchmarks CLI path, launch.py's auto-repair subprocess)
    all rely on this never crashing, not just the fetch/rank step inside it."""
    catalog_path = Path(catalog_path) if catalog_path else _DEFAULT_CATALOG_PATH
    md_path = Path(md_path) if md_path else _DEFAULT_MD_PATH

    try:
        with open(catalog_path, encoding="utf-8") as f:
            data = json.load(f)

        if not force and not _is_stale(data.get("fetched_at")):
            return False

        families = load_curated_families()
        benchmark_rows = fetch_benchmarks()
        for tier_name, tier in data["tiers"].items():
            floor = _TIER_FLOORS.get(tier_name, {"min_ram_gb": 0, "min_vram_gb": 0})
            tier["benchmark_choices"] = rank_candidates(
                families, benchmark_rows,
                tier_min_ram_gb=floor["min_ram_gb"],
                tier_min_vram_gb=floor["min_vram_gb"],
            )

        data["fetched_at"] = datetime.now(timezone.utc).isoformat()
        with open(catalog_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        md_path.write_text(_render_markdown(data), encoding="utf-8")
    except Exception:
        # Silent fallback per spec - leave the existing cache file untouched.
        return False

    return True


if __name__ == "__main__":
    import sys
    forced = "--force" in sys.argv
    changed = refresh(force=forced)
    print("Catalog refreshed." if changed else "Catalog cache still fresh - no fetch performed.")
